name: deploy

on:
  push:
    branches:
      - main
jobs:
  be-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: SSH-deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{secrets.VPC_HOST}}
          username: ${{secrets.VPC_USER}}
          password: ${{secrets.VPC_PASSWORD}}
          port: ${{secrets.VPC_PORT}}
          script: |
            whoami
            cd /home/web08-ByeolSoop
            git pull origin main
            cd BE
            npm install --force
            npm run build
            npm restart
