name: Build and Push frontend

on:
  push:
    paths:
      - "FE/**"
    branches:
      - main

jobs:
  build-and-push-frontend:
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Docker Compose
        run: |
          sudo apt-get update
          sudo apt-get install -y curl
          sudo curl -L "https://github.com/docker/compose/releases/download/1.27.4/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose
          docker-compose --version

      - name: Login to NCP Container Registry
        uses: docker/login-action@v3
        with:
          registry: byeolsoop-registry.kr.ncr.ntruss.com
          username: ${{ secrets.API_ACCESS_KEY }}
          password: ${{ secrets.API_SECRET_KEY }}

      - name: Build and Push Frontend Docker Image
        run: |
          docker build -t byeolsoop-registry.kr.ncr.ntruss.com/frontend:byeolsoop -f ./docker/fe/Dockerfile .
          docker push byeolsoop-registry.kr.ncr.ntruss.com/frontend:byeolsoop

  pull-and-deploy:
    runs-on: ubuntu-20.04
    needs: build-and-push-frontend

    steps:
      - name: SSH-deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{secrets.VPC_HOST}}
          username: ${{secrets.VPC_USER}}
          password: ${{secrets.VPC_PASSWORD}}
          port: ${{secrets.VPC_PORT}}
          script: |
            cd /home/docker-byeolsoop
            docker system prune -a
            docker pull byeolsoop-registry.kr.ncr.ntruss.com/frontend:byeolsoop
            docker compose up --force-recreate --build -d --quiet-pull 2>log.out
            cat log.out
